title: EconometriCode
author: Vinicius Lima
email: viniciuslimafgv at gmail dot com

description: I have always developed some programs to understand and explain concepts in Probability, Statistics and Econometrics. Also, I have spent hours in building graphs or in data wrangling. This blog is the way I found to organize most of this work forming a kind of personal libray that I share with people who may find it useful.

Enjoy ;)


show_excerpts: true # set to true to show excerpts on the homepage

excerpt_separator: <!--end_excerpt-->

theme: minima

permalink: /:categories/:title/
