title: EconometriCode
author: Vinicius Lima
email: viniciuslimafgv at gmail dot com

show_excerpts: true # set to true to show excerpts on the homepage

excerpt_separator: <!--end_excerpt-->

theme: minima

permalink: /:categories/:title/
